### ISSUE TITLE
Discussion: Has any had any troubles with this package?

### ISSUE THREAD

**Issue by jerairrest** [incube8/codeception-lumen#5]
If not, can we get rid of the "This module is currently in development and is not recommended for use." from the readme.md to maybe get a little more traction on this project. :D

**Comment by delatbabel** [comment]
Unfortunately I have had neither success nor failure reports on this module.  I have tried constructing a lumen app with this module included but it doesn't appear to have worked to any great extent.  There have been some recent changes to Lumen so I may try again shortly.

**Comment by jerairrest** [comment]
Well, log an issue and lets get this thing stable. :D

**Comment by nickcv-ln** [comment]
it turns out that there is already a Lumen module in the latest version of codeception.
I don't know when it was added, but it works fine.

**Comment by delatbabel** [comment]
Yes, I think that this package is now obsolete, there is now a codeception plugin for Lumen so this package is no longer required.
